//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmatrix_student_form_data
    {
        public int csfd_key { get; set; }
        public string csfd_data { get; set; }
        public Nullable<int> csfd_csftd_key { get; set; }
        public Nullable<int> csfd_usr_key { get; set; }
        public Nullable<int> csfd_cmp_key { get; set; }
        public string csfd_json_list { get; set; }
        public Nullable<System.Guid> csftd_record_guid { get; set; }
        public Nullable<bool> csfd_is_for_event { get; set; }
        public Nullable<int> csfd_cee_key { get; set; }
    
        public virtual cmatrix_student_form_template_details cmatrix_student_form_template_details { get; set; }
    }
}
