//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmatrix_contact_form_template_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cmatrix_contact_form_template_details()
        {
            this.cmatrix_contact_form_data = new HashSet<cmatrix_contact_form_data>();
        }
    
        public int ccftd_key { get; set; }
        public Nullable<int> ccftd_cmp_key { get; set; }
        public Nullable<int> ccftd_cab_type { get; set; }
        public int ccftd_attr_type { get; set; }
        public int ccftd_order { get; set; }
        public string ccftd_field_name { get; set; }
        public string ccftd_field_label { get; set; }
        public string ccftd_field_info { get; set; }
        public Nullable<int> ccftd_cab_col_name { get; set; }
        public int ccftd_col_span { get; set; }
        public bool ccftd_is_req { get; set; }
        public bool ccftd_is_active { get; set; }
        public Nullable<bool> ccftd_is_default { get; set; }
        public Nullable<int> ccftd_tab_type { get; set; }
        public string ccftd_options { get; set; }
        public Nullable<int> ccftd_ddl_type { get; set; }
        public string ccftd_field_placeholder { get; set; }
        public string ccftd_error_message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmatrix_contact_form_data> cmatrix_contact_form_data { get; set; }
    }
}
