//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmatrix_contact_form_data
    {
        public int ccfd_key { get; set; }
        public Nullable<int> ccfd_ccb_key { get; set; }
        public string ccfd_data { get; set; }
        public Nullable<int> ccfd_ccftd_key { get; set; }
        public Nullable<int> ccfd_atk_key { get; set; }
    
        public virtual cmatrix_contact_form_template_details cmatrix_contact_form_template_details { get; set; }
    }
}
