//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmatrix_contact
    {
        public int ccf_key { get; set; }
        public string ccf_name { get; set; }
        public System.DateTime ccf_created_date { get; set; }
        public Nullable<bool> ccf_is_deleted { get; set; }
        public Nullable<bool> ccef_is_selected { get; set; }
        public Nullable<int> ccef_cmp_key { get; set; }
        public Nullable<bool> ccf_is_enrollment_form_submitted { get; set; }
    }
}
