//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmatrix_student_form_template_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cmatrix_student_form_template_details()
        {
            this.cmatrix_student_form_data = new HashSet<cmatrix_student_form_data>();
        }
    
        public int csftd_key { get; set; }
        public Nullable<int> csftd_cmp_key { get; set; }
        public int csftd_attr_type { get; set; }
        public int csftd_order { get; set; }
        public string csftd_field_name { get; set; }
        public string csftd_field_label { get; set; }
        public string csftd_field_info { get; set; }
        public Nullable<int> csftd_cab_col_name { get; set; }
        public int csftd_col_span { get; set; }
        public bool csftd_is_req { get; set; }
        public bool csftd_is_active { get; set; }
        public Nullable<bool> csftd_is_default { get; set; }
        public Nullable<int> csftd_tab_type { get; set; }
        public string csftd_options { get; set; }
        public Nullable<int> csftd_ddl_type { get; set; }
        public string csftd_field_placeholder { get; set; }
        public Nullable<int> csftd_cses_key { get; set; }
        public Nullable<int> csftd_cab_type { get; set; }
        public string csftd_validation_msg { get; set; }
        public Nullable<int> csftd_app_sync_key { get; set; }
    
        public virtual cmatrix_student_enrollment_section cmatrix_student_enrollment_section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmatrix_student_form_data> cmatrix_student_form_data { get; set; }
    }
}
