//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnSetting
    {
        public int Id { get; set; }
        public string GridName { get; set; }
        public string ColumnText { get; set; }
        public string ColumnType { get; set; }
        public string ColumnFilterId { get; set; }
        public string ColumnWidth { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<int> ColumnOrder { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    }
}
