//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsJava { get; set; }
        public Nullable<bool> IsCsharp { get; set; }
        public Nullable<bool> IsPaython { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string CityIds { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual tbl_city tbl_city { get; set; }
    }
}
